### ISSUE TITLE
Unités API hydrométrie Hub'Eau

### ISSUE THREAD

**Issue by tvilmus** [christophe77/hubeau-react-exemple#1]
Bonjour, et bravo pour votre Wrapper !

J'ai committé vos ajouts (désolé pour le délai)

Juste une petite remarque par rapport aux unités des résultats diffusés par l'API hydrométrie
https://hubeau.eaufrance.fr/page/api-hydrometrie - Exposition des données
> Les observations sont exprimées dans les unités suivantes :
>     mm pour les hauteurs d'eau (diviser par 1000 pour convertir en mètres) ;
>     l/s pour les débits (diviser par 1000 pour convertir en m3/s).

Ainsi le 06/01/22 à 15h à la station de Givry :  
la hauteur est de 881mm soit 0.881 m et non 0.0881
le débit est de 583 000 l/s soit 583 m3/s et non 583000

Continuez ces beaux développements et n'hésitez pas à nous solliciter pour toute question!
Bien cordialement,
Thierry

**Comment by christophe77** [comment]
Merci, je n'étais pas certain des unités à utiliser, je vais corriger ça!

**Comment by christophe77** [comment]
Corrigé
